default: &default
  host: localhost
  user: dlacreme
  password: toto
  adapter: postgres

development:
  <<: *default
  db: pilbear_development

test:
  <<: *default
  db: pilbear_test

development:
  <<: *default