default: &default
  host: localhost
  user: local
  password: pass
  adapter: postgres

development:
  <<: *default
  db: pls_development

test:
  <<: *default
  db: pls_test

production:
  <<: *default
  db: pls_prod
