default: &default
  host: localhost
  user: postgres
  password: toto42
  adapter: postgres

development:
  <<: *default
  db: pilbear_development

test:
  <<: *default
  db: pilbear_test

production:
  <<: *default
  db: d6c3325mivu0ga
  host: ec2-184-72-235-80.compute-1.amazonaws.com
  port: 5432
  user: dounpppiruqezn
  password: 814f0a49cd4bbb294d1cc8dd89fca8e56ad5be5dbd4b497f0eb516ba1f8bbb95
